name: run-test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Setup .NET SDK (8.0)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
 
    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear
 
    - name: Clean previous build
      run: |
        rm -rf ./bin
        rm -rf ./obj
 
    - name: Restore dependencies
      run: dotnet restore
 
    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal

      
    - name: Install Allure CLI
      run: |
       sudo apt-get update
       sudo apt-get install -y default-jre unzip
       DOWNLOAD_URL=$(curl -s https://api.github.com/repos/allure-framework/allure2/releases/latest \
         | grep browser_download_url \
         | grep 'allure-.*\.zip' \
         | cut -d '"' -f 4)
       echo "Downloading from: $DOWNLOAD_URL"
       curl -o allure.zip -L "$DOWNLOAD_URL"
       unzip allure.zip -d allure
       sudo mv allure /opt/allure
       echo "/opt/allure/bin" >> $GITHUB_PATH

    - name: Run tests and collect Allure results
      run: dotnet test --no-build --configuration Release --logger "console;verbosity=normal" --results-directory "allure-results"

    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o _site

    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site